#################################################################
## Docker compose file for pulling and configuring MSSQL image ##
#################################################################

version: '3.8'

services:

  mssql-db:
    build:
      context: .
      dockerfile: Dockerfile # or path to your Dockerfile if it's not in the root
    environment:
      ACCEPT_EULA: ${EULA}
      SA_PASSWORD: ${PASSWORD}
    ports:
      - "${PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./assets/sql:/sqlscripts


volumes:
  mssql_data:
