#################################################################
## Docker compose file for pulling and configuring MSSQL image ##
#################################################################

version: '3.8'

services:

  mssql-db:
    image: mcr.microsoft.com/mssql/server:${VERSION}
    environment:
      ACCEPT_EULA: ${EULA}
      SA_PASSWORD: ${PASSWORD}
    ports:
      - "${PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
